import os
import sys
import csv
import numpy as np
import torch
import cv2
from torch.utils.data import DataLoader

from dotenv import load_dotenv

load_dotenv()

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from gradio.model import get_model, soft_argmax_2d
from infant_dataset import get_train_test_split

# config
NUM_LANDMARKS = 23
NUM_STAGES = 6
CKPT_23 = "../infant_ear_model_23lm_best.pth"
OUTPUT_DIR = "test_outputs/accuracy"
VIS_DIR = "test_outputs/accuracy/visualizations"
IMAGES_DIR = os.environ.get("INFANT_IMAGES_DIR", "")
# testing threshold (0-1 scale)
ERROR_THRESHOLD_PASS = 0.25

DEVICE = "cuda" if torch.cuda.is_available() else "cpu"
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(VIS_DIR, exist_ok=True)

PASSED = 0
FAILED = 0


def check(name, condition, detail=""):
    global PASSED, FAILED
    if condition:
        print(f"  [PASS] {name}")
        PASSED += 1
    else:
        print(f"  [FAIL] {name}  {detail}")
        FAILED += 1


# load model
print("\n======== Accuracy Evaluation ========")
model_23 = get_model(NUM_LANDMARKS, NUM_STAGES).to(DEVICE)
if os.path.exists(CKPT_23):
    model_23.load_state_dict(torch.load(CKPT_23, map_location=DEVICE))
    print(f"  Loaded {CKPT_23}")
else:
    print(f"  WARNING: {CKPT_23} not found")
model_23.eval()

_, test_dataset = get_train_test_split(num_landmarks=NUM_LANDMARKS)
test_loader = DataLoader(test_dataset, batch_size=1, shuffle=False)

all_errors = []
rows = []

with torch.no_grad():
    for idx, (imgs, target_heatmaps) in enumerate(test_loader):
        imgs = imgs.to(DEVICE)

        # Ground truth - ecode from heatmaps generated by manual annotations
        gt = soft_argmax_2d(target_heatmaps, normalize=True).cpu().numpy().squeeze()

        out = model_23(imgs)
        if isinstance(out, (list, tuple)):
            heat = out[-1]
        elif out.ndim == 5:
            heat = out[:, -1]
        else:
            heat = out

        pred = soft_argmax_2d(heat, normalize=True).cpu().numpy().squeeze()
        errors = np.sqrt(np.sum((pred - gt) ** 2, axis=1))
        mean_err = errors.mean()
        all_errors.append(mean_err)

        img_name = test_dataset.image_files[idx]

        img_path = os.path.join(IMAGES_DIR, img_name)
        orig = cv2.imread(img_path)
        if orig is not None:
            H, W = orig.shape[:2]
            pred_px = pred * np.array([W - 1, H - 1])
            gt_px = gt * np.array([W - 1, H - 1])
            for x, y in pred_px:
                cv2.circle(
                    orig, (int(x), int(y)), 5, (0, 0, 255), -1
                )  # red = predicted
            for x, y in gt_px:
                cv2.circle(
                    orig, (int(x), int(y)), 5, (0, 255, 0), -1
                )  # green = ground truth
            cv2.imwrite(os.path.join(VIS_DIR, f"result_{img_name}"), orig)

        rows.append(
            {
                "image": img_name,
                "mean_error": round(mean_err, 6),
                **{f"lm{i+1}_error": round(errors[i], 6) for i in range(NUM_LANDMARKS)},
            }
        )

all_errors = np.array(all_errors)

print(f"\n  --- Overall ({len(all_errors)} images) ---")
print(f"  Average error : {all_errors.mean():.6f}")
print(f"  Median error  : {np.median(all_errors):.6f}")
print(f"  Std deviation : {all_errors.std():.6f}")
print(f"  Min error     : {all_errors.min():.6f}")
print(f"  Max error     : {all_errors.max():.6f}")


# Verify average prediction error is within acceptable threshold
check(
    f"Average error below threshold ({ERROR_THRESHOLD_PASS})",
    all_errors.mean() < ERROR_THRESHOLD_PASS,
    f"Got {all_errors.mean():.6f}",
)

# Verify no images produced NaN errors
check("No images with NaN error", not any(np.isnan(e) for e in all_errors))

csv_path = os.path.join(OUTPUT_DIR, "accuracy_results.csv")
fieldnames = ["image", "mean_error"] + [f"lm{i+1}_error" for i in range(NUM_LANDMARKS)]
with open(csv_path, "w", newline="") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)
print(f"\n  Results saved to {csv_path}")
print(f"  Visualizations saved to {VIS_DIR}/")

# summary
print(f"\n======== Summary ========")
print(f"  PASSED: {PASSED}")
print(f"  FAILED: {FAILED}")
